AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Lambda with partial batch failure (SQS Event Source Mapping)


Resources:
  SourceDlqQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: SourceDlqQueue

  SourceQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: SourceQueue
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt SourceDlqQueue.Arn
        maxReceiveCount: 2

  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: "LambdaPartialBatch"
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: LambdaSQSPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - sqs:ReceiveMessage
                  - sqs:DeleteMessage
                  - sqs:GetQueueAttributes
                Resource: !GetAtt SourceQueue.Arn
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "*"

  PartialBatchLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: PartialBatchLambda
      Handler: index.handler
      Runtime: nodejs18.x
      CodeUri: ./lambda/
      Role: !GetAtt LambdaExecutionRole.Arn
      Events:
        SQSTrigger:
          Type: SQS
          Properties:
            Queue: !GetAtt SourceQueue.Arn
            BatchSize: 5
            FunctionResponseTypes:
              - ReportBatchItemFailures