AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Lambda with code deploy

Globals:
  Function:
      MemorySize: 128

Resources:
  CodeDeployServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: codedeploy.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSCodeDeployRoleForLambda
      Policies:
        - PolicyName: LambdaInvokePermissions
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - lambda:InvokeFunction
                  - lambda:GetFunction
                  - lambda:GetFunctionConfiguration
                  - lambda:UpdateFunctionCode
                  - lambda:UpdateFunctionConfiguration
                  - lambda:GetAlias
                  - lambda:UpdateAlias
                  - lambda:PublishVersion
                Resource: '*'

  HelloFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: HelloFunction
      CodeUri: hello/
      Handler: app.lambda_handler
      Runtime: python3.13
      Timeout: 3
      AutoPublishAlias: live
      DeploymentPreference:
        Type: Canary10Percent5Minutes
        Role: !GetAtt CodeDeployServiceRole.Arn
        Alarms:
          - !Ref HelloFunctionErrorsAlarm
        Hooks:
          PreTraffic: !Ref PreTrafficHook
          PostTraffic: !Ref PostTrafficHook
      Events:
        Api:
          Type: Api
          Properties:
            Path: /hello
            Method: get

  PreTrafficHook:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: PreTrafficHook
      Runtime: python3.13
      CodeUri: hooks/
      Handler: pretraffic.lambda_handler
      Timeout: 60
      Policies:
        - Statement:
            Effect: Allow
            Action:
              - codedeploy:PutLifecycleEventHookExecutionStatus
            Resource: '*'
      DeploymentPreference:
        Enabled: false

  PostTrafficHook:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: python3.13
      FunctionName: PostTrafficHook
      CodeUri: hooks/
      Handler: posttraffic.lambda_handler
      Timeout: 60
      Policies:
        - Statement:
            Effect: Allow
            Action:
              - codedeploy:PutLifecycleEventHookExecutionStatus
            Resource: '*'
      DeploymentPreference:
        Enabled: false

  HelloFunctionErrorsAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: HelloFunctionErrorsAlarm
      Namespace: AWS/Lambda
      MetricName: Errors
      Dimensions:
        - Name: FunctionName
          Value: !Ref HelloFunction
      Statistic: Sum
      Period: 60
      EvaluationPeriods: 1
      Threshold: 1
      ComparisonOperator: GreaterThanOrEqualToThreshold
      TreatMissingData: notBreaching

Outputs:
  HelloFunctionApi:
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello"